### ISSUE TITLE
Problem storing verb

### ISSUE THREAD

**Issue by ghost** [jgsmitty/Experience-API-for-Moodle#1]
Thanks for a good plugin!

I am trying to send an xAPI request to Moodle from a simple Cordova/Phonegap app. The client is implemented in javascript, and uses the library and the techniques found here:
http://tincanapi.co.uk/pages/Building_your_first_Tin_Can_API_activity.html

This library sends what appears to me to be a valid xAPI statement, but when the plugin tries to store it to DB, it gives me an error ("Coding error detected, it must be fixed by a programmer:..."). It seems the problem is that one of the values we are trying to store to the DB is of type "stdClass". After some debugging, I found that the "Verb" part of the statement is the problem, and that it happens when "$DB->insert_record()" is called in "local_tcapi_store_statement".

The javascript library sends a Verb that looks something like this:

```
{
    id : "http://activitystrea.ms/specs/json/schema/activity-schema.html#read",
    display : {
        "en-US":"read" 
    }
}
```

And that is converted to a PHP stdClass with the same structure when it reaches Moodle. However, it is never converted to a string, which is what the database table expects.

I'm not entirely sure how to handle this. I'm open to the possibility that I am doing something wrong here, but from what I gather from the xAPI spec, the statement I am sending is correct, and the xAPI plugin is unable to handle that statement.

I thought about using the first "display" element, but not only does it feel wrong, the xAPI spec clearly says not to do such a thing. Using "id" would be a better choice, but the best would be to store the whole object. However the "verb" column in the database is 50 characters long (in MySQL anyway).

Thanks,
Morten Krane

**Comment by garemoko** [comment]
Hi Morten,
Thanks for looking up my tutorial on tincanapi.co.uk - I hope you found it helpful!

This isn't my plugin, but I think I can see what the issue is here. Jamie's plugin was built to support Tin Can courses built with Articulate Storyline which uses an old beta version of Tin Can API whereas my tutorial gets you to set he version as 0.95. Actually, you should be using the latest version of the specification 1.01 (I need to update my tutorial).

As I understand it Jamie's no longer working on this plugin, but there are other developments involving Tin can in Moodle afoot (see https://moodle.org/plugins/browse.php?list=set&id=48 for two examples). Your choices are to either contribute to or wait for Tin Can support in Moodle to mature, or set your e-learning to use Tin Can 0.9 (which isn't ideal). 

``` javascript
var myLRS = new TinCan.LRS({
    endpoint:"https://your.lrs.com/endpoint", 
    version: "0.9",
    auth: 'Basic ' + Base64.encode("<account id>" + ':' + "<password>")
})
```

**Comment by ghost** [comment]
Hi,

Thanks for answering so quickly. Your tutorial was very helpful indeed, I was afraid that I had to implement the whole client-side from scratch, which probably would have blown the budget of the project. But with your tutorial and Rustici's library (with your fixes), a lot has been done for me. No need to implement the wheel more than once.

I tried setting the version to 0.9, and now the statement is properly stored with no errors. Great! However, the verb stored in Moodle seems to be "experienced" even if I sent "read". Maybe that's the way its supposed to be? I'm not sure if that has any real implications, the whole statement is after all stored in the "statement" column. I am rather new to both xAPI and Moodle, and the app is currently at a proof-of-concept stage, so I think we can leave it at that for now.

Solved my problem, so I'm closing this issue. At least for now.

Thank you very much for your help!

Morten

**Comment by garemoko** [comment]
Yes, that's the problem with 0.9 - a limited collection of verbs. Read isn't one of them!

Date: Thu, 14 Nov 2013 05:16:58 -0800
